Updated vendored dependencies.
We recently updated our s3 compatible object gateway to use https. Only changing
the url scheme from http to https, the pipeline step failed consistently with:

```
RequestError: send request failed
caused by: Put https://(redacted): EOF
```

By simply updating the vendored packages (and thus pulling in the latest version
of aws-sdk-go), we were able to eliminate the error.